#!/usr/bin/env ruby

def main_branch?(branch_name)
  /\A(master|main)\z/.match? branch_name
end

def restrict_branches(branch_name)
  return if /\A(y|yes)\z/ =~ ENV['GIT_ALLOW_PUSH_MAIN_BRANCH']

  fail "Don't push default branch!!! (master or main)\nSet 'GIT_ALLOW_PUSH_MAIN_BRANCH'" if main_branch? branch_name
end

def use_force_option?(command)
  /\s(--force|-f)/.match?(command)
end

def restrict_force_push(command)
  return if /\A(y|yes)\z/ =~ ENV['GIT_ALLOW_FORCE_PUSH']

  fail "Don't use --force option!!!\nSet 'GIT_ALLOW_FORCE_PUSH'" if use_force_option? command
end

def main
  input = STDIN.read
  command = `ps -o command= -p #{Process.ppid}`.chomp

  restrict_force_push command

  input.each_line do |line|
    _, _, remote_ref, _ = line.chomp.split
    next if remote_ref.nil? || remote_ref.empty?

    branch_name = remote_ref.gsub('refs/heads/', '')
    restrict_branches branch_name
  end

  if system('command -v git-lfs > /dev/null 2>&1')
    IO.popen(['git', 'lfs', 'pre-push', *ARGV], 'w') { |io| io.write(input) }
  end
rescue => e
  STDERR.puts e.message
  exit 1
end
main if __FILE__ == $0
