#!/usr/bin/env ruby

def main_branch?(branch_name)
  /\A(master|main)\z/.match? branch_name
end

def restrict_branches(branch_name)
  return if /\A(y|yes)\z/ =~ ENV['GIT_ALLOW_PUSH_MAIN_BRANCH']

  fail "Don't push default branch!!! (master or main)" if main_branch? branch_name
end

def use_force_option?(command)
  /--force|-f/.match?(command)
end

def restrict_force_push(command)
  return if /\A(y|yes)\z/ =~ ENV['GIT_ALLOW_FORCE_PUSH']

  fail "Don't use --force option!!!" if use_force_option? command
end

def main
  _, _, remote_ref, _ = STDIN.gets.chomp.split
  branch_name = remote_ref.gsub('refs/heads/', '')
  command = `ps -o command= -p #{Process.ppid}`.chomp

  restrict_branches branch_name
  restrict_force_push command
rescue => e
  STDERR.puts e.message
  exit 1
end
main if __FILE__ == $0
