#
# Toml
#
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#
# Ruby
#
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

#
# SASS/SCSS
#
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_path = '.scss'

#
# Ansible
#
[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = ['ansible']

#
# Nginx
#
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

#
# LTSV
#
[[plugins]]
repo = 'moznion/vim-ltsv'
on_ft = ['ltsv']

#
# Fluentd
#
[[plugins]]
repo = 'itkq/fluentd-vim'
on_ft = ['fluentd']

#
# Terraform
#
[[plugins]]
repo     = 'hashivim/vim-terraform'
on_ft    = ['terraform']

#
# Dockerfile
#
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

#
# Rego
#
[[plugins]]
repo = 'tsandall/vim-rego'
on_ft = ['rego']
