#
# Overhaul
#
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap ub     :Denite buffer<CR>
nnoremap uf     :Denite file_mru<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'w0rp/ale'

#
# Completion
#
[[plugins]]
repo     = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

#
# Interface
#
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
\   'active': {
\       'left': [ [ 'mode', 'paste' ],
\               [ 'readonly', 'filepath', 'lineinfo' ] ],
\       'right': [ ['percent' ],
\                  [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
\   },
\   'component_function': {
\       'filepath': 'Filepath'
\   }
\}
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_enabled = 1
let g:gitgutter_realtime = 1
let g:gitgutter_eager = 0
let g:gitgutter_map_keys = 0
let g:gitgutter_sign_added = '.'
let g:gitgutter_sign_modified = '.'
let g:gitgutter_sign_removed = '.'
let g:gitgutter_sign_removed_first_line = '.'
let g:gitgutter_sign_modified_removed = '.'

nnoremap gs :GitGutterToggle<CR>
nnoremap gn :GitGutterNextHunk<CR>
nnoremap gb :GitGutterPrevHunk<CR>
'''

#
# Colorscheme
#
[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
let g:hybrid_use_iTerm_colors = 1
'''

#
# Formatter
#
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
'''

#
# Support tools
#
[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = '''
let g:switch_mapping = ""

nnoremap <SPACE><SPACE> :<C-u>Switch<CR>
'''

[[plugins]]
repo = 'syui/airsave.vim'
hook_add = '''
let g:auto_write = 1
'''

#
# Others
#
[[plugins]]
repo = 'Shougo/vinarise.vim'
